mineflayer = require('mineflayer')
cmd = require('mineflayer-cmd').plugin
fs = require('fs')
rawdata = fs.readFileSync('config.json')
data = JSON.parse(rawdata)
lasttime = -1
moving = 0
connected = 0
actions = [
  'forward'
  'back'
  'left'
  'right'
]
lastaction = undefined
pi = 3.14159
moveinterval = 2
# 2 second movement interval
maxrandom = 5
# 0-5 seconds added to movement interval (randomly)
host = data['ip']
username = data['name']
nightskip = data['auto-night-skip']
bot = mineflayer.createBot(
  host: host
  username: username)

getRandomArbitrary = (min, max) ->
  Math.random() * (max - min) + min

bot.loadPlugin cmd
bot.on 'login', ->
  console.log 'Logged In'
  bot.chat 'hello'
  return
bot.on 'time', (time) ->
  if nightskip == 'true'
    if bot.time.timeOfDay >= 13000
      bot.chat '/time set day'
  if connected < 1
    return
  if lasttime < 0
    lasttime = bot.time.age
  else
    randomadd = Math.random() * maxrandom * 20
    interval = moveinterval * 20 + randomadd
    if bot.time.age - lasttime > interval
      if moving == 1
        bot.setControlState lastaction, false
        moving = 0
        lasttime = bot.time.age
      else
        yaw = Math.random() * pi - (0.5 * pi)
        pitch = Math.random() * pi - (0.5 * pi)
        bot.look yaw, pitch, false
        lastaction = actions[Math.floor(Math.random() * actions.length)]
        bot.setControlState lastaction, true
        moving = 1
        lasttime = bot.time.age
        bot.activateItem()
  return
bot.on 'spawn', ->
  connected = 1
  return
bot.on 'death', ->
  bot.emit 'respawn'
  return

# ---
# generated by js2coffee 2.2.0
